# Generated by Django 3.1.3 on 2022-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=10)),
                ('prod_name', models.CharField(max_length=100)),
                ('unit_cost', models.FloatField(max_length=100)),
                ('tot_cost', models.FloatField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('photo', models.CharField(max_length=500)),
                ('d_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=10)),
                ('prod_name', models.CharField(max_length=100)),
                ('unit_cost', models.FloatField(max_length=100)),
                ('tot_cost', models.FloatField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('d_date', models.CharField(max_length=100)),
                ('stz', models.CharField(max_length=100)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='prod_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=10)),
                ('cat_name', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=100)),
                ('cost', models.FloatField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('stz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('stz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users_locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('addr_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('zip', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
