# Generated by Django 3.1.3 on 2022-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sid',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
