# Generated by Django 3.1.3 on 2022-04-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_products_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sid',
            field=models.CharField(default='SELLER1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='sid',
            field=models.CharField(default='SELLER1', max_length=100),
            preserve_default=False,
        ),
    ]
